
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - restaurant-service
      - order-service

  restaurant-service:
    build: ./services/user_service
    ports:
      - "4001:4001"
    environment:
      MYSQL_ROOT_PASSWORD: English2024@
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: English2024@

  food-service:
    build: ./services/food_service
    ports:
      - "4002:4002"
    environment:
      MYSQL_ROOT_PASSWORD: English2024@
      MYSQL_DATABASE: restaurant_service
      MYSQL_USER: root
      MYSQL_PASSWORD: English2024@

  order-service:
    build: ./services/order_service
    ports:
      - "4003:4003"
    environment:
      MYSQL_ROOT_PASSWORD: English2024@
      MYSQL_DATABASE: order-service
      MYSQL_USER: root
      MYSQL_PASSWORD: English2024@
